import type { Metadata } from "next";
import { use, useState } from "react";
import { Inter } from "next/font/google";
import Nav from "./layout/Nav";
import Footer from "./layout/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carton Sport Polare",
  description: "Generated by create next app",
  // icons: [{ rel: "icon", url: "./favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='icon'
          href='./favicon.svg'
          type='image/<generated>'
          sizes='<generated>'
        />
      </head>
      <body className={inter.className + " pt-2"}>
        <main>{children}</main>
      </body>
    </html>
  );
}
